import type { EntityConfig } from '@/lib/harness/types';

export const dailyEntityConfig: EntityConfig = {
  type: 'daily',
  name: 'Daily OS',
  mission: 'Produce a complete morning brief covering inbox, calendar, health, news, and work prep — then stay available to action commands throughout the day.',
  rootAgentId: 'daily-orchestrator',
  agentIds: [
    'daily-orchestrator',
    'inbox-triage',
    'calendar-reader',
    'health-briefer',
    'news-curator',
    'work-prep',
  ],
  availableTools: [
    'spawn_agent',
    'wait_for_agents',
    'write_state',
    'read_state',
    'kb_read',
    'kb_write',
    'queue_action',
    'gmail_read',
    'calendar_read',
    'news_search',
    'web_search',
    'send_message',
    'request_human_input',
  ],
  autonomy: 'semi-auto',
  consensusThreshold: 0.60,
  costConfig: {
    maxTokensPerRun: 80_000,
    maxAgentsPerRun: 10,
    maxTierDepth: 2,
    realWorldToolMode: 'dry-run',
  },
  buildInitialContext: (_input) => ({
    currentDate: new Date().toISOString().split('T')[0],
    currentTime: new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
    dayOfWeek: new Date().toLocaleDateString('en-GB', { weekday: 'long' }),
  }),
  buildInitialTask: (_input) => ({
    description: `Today is ${new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}. Produce the morning brief.`,
    contextKeys: [],
  }),
};

export const dispatchEntityConfig: EntityConfig = {
  type: 'daily',
  name: 'Dispatch',
  mission: 'Execute the user command as efficiently as possible.',
  rootAgentId: 'dispatcher',
  agentIds: [
    'dispatcher',
    'inbox-triage',
    'calendar-reader',
    'shared-researcher',
  ],
  availableTools: [
    'spawn_agent',
    'wait_for_agents',
    'write_state',
    'read_state',
    'kb_read',
    'kb_write',
    'queue_action',
    'gmail_read',
    'calendar_read',
    'web_search',
    'news_search',
    'web_fetch',
    'send_message',
    'request_human_input',
  ],
  autonomy: 'semi-auto',
  consensusThreshold: 0.60,
  costConfig: {
    maxTokensPerRun: 30_000,
    maxAgentsPerRun: 4,
    maxTierDepth: 2,
    realWorldToolMode: 'dry-run',
  },
  buildInitialContext: (input) => ({
    command: input.command ?? '',
    currentDate: new Date().toISOString().split('T')[0],
    currentTime: new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
  }),
  buildInitialTask: (input) => ({
    description: `Execute this command: "${input.command ?? ''}"`,
    contextKeys: [],
  }),
};
